 spring:
  cloud:
    gateway:
      routes:
      - id: service-product
        uri:  lb://service-product
        predicates:
          - Path=/api/products/**
          - Method=GET, POST
        filters:
        - StripPrefix=2
        - name: ExampleCookie
          args:
            message: Hey! My custom message
            cookieName: user
            cookieValue: Andres
      - id: service-items
        uri:  lb://service-items
        predicates:
          - Path=/api/items/**
        filters:
        - StripPrefix=2  
        - AddRequestHeader=token-request, 123456
        - AddResponseHeader=token-response, 12345678
        - AddRequestParameter=name, andres
              